#!/bin/bash
#将来可能可以换成apt-metalink来直接用种子/链接下载

echo "Spark Store Install script.星火商店安装脚本"

#################检测文件是否存在
if [ $# -eq 0 ];then
echo "没有接收到参数，退出"
echo "用法：$0 deb路径"
exit
fi

if [ ! -f "$1" ]
then
	echo "文件不存在"
	exit 1
fi

deb_path="$(cd "$(dirname "$1")";pwd)/$(basename $1)"

#################root校验+要密码
if [ "$(id -u)" != "0" ]
then
	echo "ssinstall需要在root下运行";
	pkexec ssinstall "$deb_path"
	exit
fi




##################apt-fast/metalink测试
DEPEND="这里一定会安装所以放弃处理"
isuos=`cat /etc/os-release | grep UnionTech`
###########################有root权限时




if [ "$DEPEND" != "" ]  && [ "$isuos" != "" ]; then
echo "UOS中系统依赖无法使用第三方下载工具，放弃使用apt-fast"
echo ----------------------------------------------------------------------------------
dpkg -i $1 || /usr/local/bin/ss-apt-fast ssupdate && bwrap --dev-bind / / --bind '/opt/durapps/spark-store/bin/apt-fast-conf/sources.list.d/sparkstore.list' /etc/apt/sources.list.d/sparkstore.list apt update && sudo bwrap --dev-bind / / --bind '/opt/durapps/spark-store/bin/apt-fast-conf/sources.list.d/sparkstore.list' /etc/apt/sources.list.d/sparkstore.list apt install -yf
fi

if  [ "$DEPEND" != "" ]  && [ "$isuos" = "" ]; then
echo "检测到apt-fast，使用ss-apt-fast进行多线程下载加速"
echo ----------------------------------------------------------------------------------
dpkg -i $1 || /usr/local/bin/ss-apt-fast ssupdate && /usr/local/bin/ss-apt-fast install -yf 
fi





