version: '1.0'
name: dtk-build-commit-20220425
displayName: dtk-build-commit
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - master
    tags:
      prefix:
        - ''
stages:
  - name: stage-200d0b6b
    displayName: docker build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: d3a72e50-a6b5-013a-3031-5e77c3ac149e
        tag: shenmo7192/spark-store-with-uos:1.${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./.gitee/Dockerfile
        context: ./target/build
        isCache: true
  - name: stage-4e566164
    displayName: 复制
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID: gitee-go
        script: |-
          # 请在此输入您想执行的脚本
          mkdir /root/workspace/deepin-community-store/spark-store/target/deb
          mv /root/workspace/deepin-community-store/spark-store/target/build/*.deb ../deb
          BUILD_ARTIFACT="/root/workspace/deepin-community-store/spark-store/target/deb"
  - name: stage-78c83955
    displayName: upload
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: package
permissions:
  - role: admin
    members: []
