version: '1.0'
name: dtk-build-commit-20220425
displayName: dtk-build-commit
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - master
    tags:
      prefix:
        - ''
stages:
  - name: stage-4e566164
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的脚本执行
        certificate: d3a72e50-a6b5-013a-3031-5e77c3ac149e
        image: https://hub.docker.com/r/shenmo7192/uos-21-dtk5.4
        command:
          - git clone https://gitee.com/deepin-community-store/spark-store
          - mkdir debs
          - cd spark-store
          - dpkg-buildpackage
          - mv *.deb ../debs
          - cd ../debs
          - curl -s --url "smtp://smtp.163.com" --mail-from "sparkstorefeedback@163.com" --mail-rcpt "shenmo@spark-app.store" --upload-file ./*.deb --user "sparkstorefeedback@163.com:YWYGLQNOPLWNNJJY"
permissions:
  - role: admin
    members: []
