version: '1.0'
name: dtk-build-commit-20220425
displayName: dtk-build-commit
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
  pr:
    branches:
      prefix:
        - ''
stages:
  - name: stage-200d0b6b
    displayName: docker build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: d3a72e50-a6b5-013a-3031-5e77c3ac149e
        tag: '1.0'
        dockerfile: ./.gitee/Dockerfile
        isCache: false
  - name: stage-78c83955
    displayName: upload
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: package
permissions:
  - role: admin
    members: []
