version: '1.0'
name: dtk-build-commit-20220425
displayName: dtk-build-commit
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
    tags:
      prefix:
        - ''
stages:
  - name: stage-4e566164
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: Build
        image: g3xe0gm8.mirror.aliyuncs.com/shenmo7192/uos-21-dtk5.4
        command:
          - dpkg-buildpackage
          - tree .
permissions:
  - role: admin
    members: []
