version: '1.0'
name: dtk-build-commit-20220425
displayName: dtk-build-commit
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
    tags:
      prefix:
        - ''
stages:
  - name: stage-4e566164
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: Build
        certificate: d3a72e50-a6b5-013a-3031-5e77c3ac149e
        image: hub.docker.com/r/jerry979/dtke:5.11.1
        command:
          - dpkg-buildpackage
          - tree .
permissions:
  - role: admin
    members: []
